name: Basic Ansible CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-playbook:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: install deps
        run: pip install ansible 

      - name: install requirements
        run: ansible-galaxy collection install -r requirements.ini

      - name: run playbook 
        run: ansible-playbook install.yml --syntax-check